
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by c
// **************************************************************************

class Images {
  const Images._();
  static String bg = 'assets/images/bg.png';
	static String loading = 'assets/images/loading.gif';
	static String star = 'assets/images/star.png';
	static String starDisabled = 'assets/images/star_disabled.png';
	static String tabSwords = 'assets/images/tab/swords.png';
	static String tabSwordsActive = 'assets/images/tab/swords_active.png';
	static String unitIcon = 'assets/images/unit_icon.webp';
	
}
