
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by c
// **************************************************************************

class Images {
  static const String bg = 'assets/images/bg.png';
	static const String loading = 'assets/images/loading.gif';
	static const String star = 'assets/images/star.png';
	static const String starDisabled = 'assets/images/star_disabled.png';
	static const String tabSwords = 'assets/images/tab/swords.png';
	static const String tabSwordsActive = 'assets/images/tab/swords_active.png';
	static const String unitIcon = 'assets/images/unit_icon.webp';
	
}
