// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/material.dart';
import 'package:pcrgvg_flutter/model/test_model.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'pages/ff_arg_page.dart';
import 'pages/home_page.dart';
import 'pages/main_page.dart';
import 'pages/spalsh_page.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'ffArgPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: FfArgPage(
          key: asT<Key?>(safeArguments['key']),
          testMode1: asT<TestMode1>(safeArguments['testMode1'])!,
        ),
        routeName: 'ffArgPage',
      );
    case 'homePage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: HomePage(
          key: asT<Key?>(safeArguments['key']),
        ),
        routeName: 'homePage',
      );
    case 'mainPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: MainPage(
          key: asT<Key?>(safeArguments['key']),
        ),
        routeName: 'mainPage',
      );
    case 'spalshPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: SpalshPage(
          key: asT<Key?>(safeArguments['key']),
        ),
        routeName: 'spalshPage',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
