// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/material.dart';
import 'package:pcrgvg_flutter/isolate/filter_task.dart';
import 'package:pcrgvg_flutter/model/models.dart';
import 'package:pcrgvg_flutter/providers/home_provider.dart';

const List<String> routeNames = <String>[
  'aboutPage',
  'collectionPage',
  'homeFilterPage',
  'homePage',
  'linkDetailPage',
  'mainPage',
  'manageCharaPage',
  'minePage',
  'resultDetailPage',
  'resultPage',
  'settingPage',
  'spalshPage',
  'taskDetailPage',
];

class Routes {
  const Routes._();

  /// 'aboutPage'
  ///
  /// [name] : 'aboutPage'
  ///
  /// [routeName] : 'aboutPage'
  ///
  /// [constructors] :
  ///
  /// AboutPage : [Key? key]
  static const _AboutPage aboutPage = _AboutPage();

  /// 'collectionPage'
  ///
  /// [name] : 'collectionPage'
  ///
  /// [routeName] : 'collectionPage'
  ///
  /// [constructors] :
  ///
  /// CollectionPage : [Key? key]
  static const _CollectionPage collectionPage = _CollectionPage();

  /// 'homeFilterPage'
  ///
  /// [name] : 'homeFilterPage'
  ///
  /// [routeName] : 'homeFilterPage'
  ///
  /// [constructors] :
  ///
  /// HomeFilterPage : [Key? key, HomeProvider(required) homeProvider]
  static const _HomeFilterPage homeFilterPage = _HomeFilterPage();

  /// 'homePage'
  ///
  /// [name] : 'homePage'
  ///
  /// [routeName] : 'homePage'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _HomePage homePage = _HomePage();

  /// 'linkDetailPage'
  ///
  /// [name] : 'linkDetailPage'
  ///
  /// [routeName] : 'linkDetailPage'
  ///
  /// [constructors] :
  ///
  /// LinkDetailPage : [Key? key, Link(required) link, String(required) bgUrl]
  static const _LinkDetailPage linkDetailPage = _LinkDetailPage();

  /// 'mainPage'
  ///
  /// [name] : 'mainPage'
  ///
  /// [routeName] : 'mainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const _MainPage mainPage = _MainPage();

  /// 'manageCharaPage'
  ///
  /// [name] : 'manageCharaPage'
  ///
  /// [routeName] : 'manageCharaPage'
  static const String manageCharaPage = 'manageCharaPage';

  /// 'minePage'
  ///
  /// [name] : 'minePage'
  ///
  /// [routeName] : 'minePage'
  ///
  /// [constructors] :
  ///
  /// MinePage : [Key? key]
  static const _MinePage minePage = _MinePage();

  /// 'resultDetailPage'
  ///
  /// [name] : 'resultDetailPage'
  ///
  /// [routeName] : 'resultDetailPage'
  ///
  /// [constructors] :
  ///
  /// ResultDetailPage : [Key? key, List<TaskFilterResult>(required) taskResult]
  static const _ResultDetailPage resultDetailPage = _ResultDetailPage();

  /// 'resultPage'
  ///
  /// [name] : 'resultPage'
  ///
  /// [routeName] : 'resultPage'
  ///
  /// [constructors] :
  ///
  /// ResultPage : [List<ResultBoss>(required) bossList]
  static const _ResultPage resultPage = _ResultPage();

  /// 'settingPage'
  ///
  /// [name] : 'settingPage'
  ///
  /// [routeName] : 'settingPage'
  ///
  /// [constructors] :
  ///
  /// SettingPage : [Key? key]
  static const _SettingPage settingPage = _SettingPage();

  /// 'spalshPage'
  ///
  /// [name] : 'spalshPage'
  ///
  /// [routeName] : 'spalshPage'
  ///
  /// [constructors] :
  ///
  /// SpalshPage : [Key? key]
  static const _SpalshPage spalshPage = _SpalshPage();

  /// 'taskDetailPage'
  ///
  /// [name] : 'taskDetailPage'
  ///
  /// [routeName] : 'taskDetailPage'
  ///
  /// [constructors] :
  ///
  /// TaskDetailPage : [Key? key, int(required) bossPrefab, Task(required) task]
  static const _TaskDetailPage taskDetailPage = _TaskDetailPage();
}

class _AboutPage {
  const _AboutPage();

  String get name => 'aboutPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _CollectionPage {
  const _CollectionPage();

  String get name => 'collectionPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _HomeFilterPage {
  const _HomeFilterPage();

  String get name => 'homeFilterPage';

  Map<String, dynamic> d({Key? key, required HomeProvider homeProvider}) =>
      <String, dynamic>{
        'key': key,
        'homeProvider': homeProvider,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'homePage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _LinkDetailPage {
  const _LinkDetailPage();

  String get name => 'linkDetailPage';

  Map<String, dynamic> d(
          {Key? key, required Link link, required String bgUrl}) =>
      <String, dynamic>{
        'key': key,
        'link': link,
        'bgUrl': bgUrl,
      };

  @override
  String toString() => name;
}

class _MainPage {
  const _MainPage();

  String get name => 'mainPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _MinePage {
  const _MinePage();

  String get name => 'minePage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _ResultDetailPage {
  const _ResultDetailPage();

  String get name => 'resultDetailPage';

  Map<String, dynamic> d(
          {Key? key, required List<TaskFilterResult> taskResult}) =>
      <String, dynamic>{
        'key': key,
        'taskResult': taskResult,
      };

  @override
  String toString() => name;
}

class _ResultPage {
  const _ResultPage();

  String get name => 'resultPage';

  Map<String, dynamic> d({required List<ResultBoss> bossList}) =>
      <String, dynamic>{
        'bossList': bossList,
      };

  @override
  String toString() => name;
}

class _SettingPage {
  const _SettingPage();

  String get name => 'settingPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _SpalshPage {
  const _SpalshPage();

  String get name => 'spalshPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _TaskDetailPage {
  const _TaskDetailPage();

  String get name => 'taskDetailPage';

  Map<String, dynamic> d(
          {Key? key, required int bossPrefab, required Task task}) =>
      <String, dynamic>{
        'key': key,
        'bossPrefab': bossPrefab,
        'task': task,
      };

  @override
  String toString() => name;
}
