// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/material.dart';
import 'package:pcrgvg_flutter/model/test_model.dart';

const List<String> routeNames = <String>[
  'ffArgPage',
  'homePage',
  'mainPage',
  'spalshPage',
];

class Routes {
  const Routes._();

  /// 'ffArgPage'
  ///
  /// [name] : 'ffArgPage'
  ///
  /// [routeName] : 'ffArgPage'
  ///
  /// [constructors] :
  ///
  /// FfArgPage : [Key? key, TestMode1(required) testMode1]
  static const _FfArgPage ffArgPage = _FfArgPage();

  /// 'homePage'
  ///
  /// [name] : 'homePage'
  ///
  /// [routeName] : 'homePage'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _HomePage homePage = _HomePage();

  /// 'mainPage'
  ///
  /// [name] : 'mainPage'
  ///
  /// [routeName] : 'mainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const _MainPage mainPage = _MainPage();

  /// 'spalshPage'
  ///
  /// [name] : 'spalshPage'
  ///
  /// [routeName] : 'spalshPage'
  ///
  /// [constructors] :
  ///
  /// SpalshPage : [Key? key]
  static const _SpalshPage spalshPage = _SpalshPage();
}

class _FfArgPage {
  const _FfArgPage();

  String get name => 'ffArgPage';

  Map<String, dynamic> d({Key? key, required TestMode1 testMode1}) =>
      <String, dynamic>{
        'key': key,
        'testMode1': testMode1,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'homePage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _MainPage {
  const _MainPage();

  String get name => 'mainPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _SpalshPage {
  const _SpalshPage();

  String get name => 'spalshPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
