// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/material.dart';
import 'package:pcrgvg_flutter/model/models.dart';
import 'package:pcrgvg_flutter/providers/home_provider.dart';

const List<String> routeNames = <String>[
  'homeFilterPage',
  'homePage',
  'mainPage',
  'minePage',
  'spalshPage',
  'taskDetailPage',
];

class Routes {
  const Routes._();

  /// 'homeFilterPage'
  ///
  /// [name] : 'homeFilterPage'
  ///
  /// [routeName] : 'homeFilterPage'
  ///
  /// [constructors] :
  ///
  /// HomeFilterPage : [Key? key, HomeProvider(required) homeProvider]
  static const _HomeFilterPage homeFilterPage = _HomeFilterPage();

  /// 'homePage'
  ///
  /// [name] : 'homePage'
  ///
  /// [routeName] : 'homePage'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _HomePage homePage = _HomePage();

  /// 'mainPage'
  ///
  /// [name] : 'mainPage'
  ///
  /// [routeName] : 'mainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const _MainPage mainPage = _MainPage();

  /// 'minePage'
  ///
  /// [name] : 'minePage'
  ///
  /// [routeName] : 'minePage'
  ///
  /// [constructors] :
  ///
  /// MinePage : [Key? key]
  static const _MinePage minePage = _MinePage();

  /// 'spalshPage'
  ///
  /// [name] : 'spalshPage'
  ///
  /// [routeName] : 'spalshPage'
  ///
  /// [constructors] :
  ///
  /// SpalshPage : [Key? key]
  static const _SpalshPage spalshPage = _SpalshPage();

  /// 'taskDetailPage'
  ///
  /// [name] : 'taskDetailPage'
  ///
  /// [routeName] : 'taskDetailPage'
  ///
  /// [constructors] :
  ///
  /// TaskDetailPage : [Key? key, int(required) bossPrefab, Task(required) task]
  static const _TaskDetailPage taskDetailPage = _TaskDetailPage();
}

class _HomeFilterPage {
  const _HomeFilterPage();

  String get name => 'homeFilterPage';

  Map<String, dynamic> d({Key? key, required HomeProvider homeProvider}) =>
      <String, dynamic>{
        'key': key,
        'homeProvider': homeProvider,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'homePage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _MainPage {
  const _MainPage();

  String get name => 'mainPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _MinePage {
  const _MinePage();

  String get name => 'minePage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _SpalshPage {
  const _SpalshPage();

  String get name => 'spalshPage';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _TaskDetailPage {
  const _TaskDetailPage();

  String get name => 'taskDetailPage';

  Map<String, dynamic> d(
          {Key? key, required int bossPrefab, required Task task}) =>
      <String, dynamic>{
        'key': key,
        'bossPrefab': bossPrefab,
        'task': task,
      };

  @override
  String toString() => name;
}
