name: build apk
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
   build:
     name: 
     runs-on: ubuntu-latest
     steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: java sdk
          uses: actions/setup-java@v1
          with:
            java-version: '11.x'
        - name: flutter
          uses: subosito/flutter-action@v1
          with:
            flutter-version: '2.2.1'
            channel: stable
        - name: build apk
          run: |
           flutter pub get
           flutter build apk
           ls build/app/outputs/flutter-apk
           mv -f build/app/outputs/flutter-apk/*-release.apk releases
           mv -f build/app/outputs/apk/release/output-metadata.json releases
        - name: build sign apk
          uses: iota9star/sign-android-release@v1.0.5
          with:
            releaseDirectory: releases
            fileRegex: .*-release.apk
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}
          env:
            BUILD_TOOLS_VERSION: "30.0.2"
        - name: Rename 
          run: |
             ls releases
             mv -f releases/output-metadata.json releases/metadata.json 
             for name in $(ls releases/*-signed.apk);do mv -f $name ${name%-signed.apk}.apk ;done
             ls releases
        - name: Commit binary files
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            branch: master
            push_options: '--force'
            commit_message: ":bookmark: Release binary files."
            file_pattern: releases/*-release.apk releases/metadata.json
        - name: Release to github
          uses: ncipollo/release-action@v1
          with:
            allowUpdates: true
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.event.inputs.TAG }}
            artifacts: "releases/*-release.apk"
        - name: Upload to oss
          uses: tvrcgo/upload-to-oss@v0.1
          with:
            key-id: ${{ secrets.OSS_KEY_ID }}
            key-secret: ${{ secrets.OSS_KEY_SECRET }}
            region: oss-cn-shanghai
            bucket: pcr-app
            asset-path: ./releases/app-release.apk
            target-path: app-release.apk


