name: oss upload
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
jobs:
  build:
     name: 
     runs-on: ubuntu-latest
     steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Upload to OSS
          uses: tvrcgo/upload-to-oss@v0.1.1
          with:
            key-id: ${{ secrets.OSS_KEY_ID }}
            key-secret: ${{ secrets.OSS_KEY_SECRET }}
            region: oss-cn-shanghai
            bucket: pcr-app
            asset-path: releases
            target-path: './'