name: oss upload
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
jobs:
  build:
     name: 
     runs-on: ubuntu-latest
     steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Upload files to OSS
          uses: jievince/upload-to-oss@v0.2.2
          with:
            key-id: ${{ secrets.OSS_KEY_ID }}
            key-secret: ${{ secrets.OSS_KEY_SECRET }}
            region: oss-cn-beijing
            bucket: pcr-icon
            asset-path: releases
            target-path: './'